language: julia
os:
    - linux
julia:
    - 0.6
    - nightly
before_script:
    - julia --color=yes -e 'Pkg.clone(pwd())'
    - julia --color=yes -e 'Pkg.add("Coverage")'
    - julia --color=yes -e 'Pkg.add("Documenter")'
    - julia --color=yes -e 'Pkg.add("Lint")'
script:
    - julia --color=yes -e 'Pkg.build("NodeNumbering")'
    - julia --color=yes -e 'Pkg.test("NodeNumbering", coverage=true)'
    - julia --color=yes -e 'cd(Pkg.dir("NodeNumbering", "test")); include("run_lint.jl")'
    - julia --color=yes -e 'cd(Pkg.dir("NodeNumbering", "docs")); include("make.jl")'
after_success:
    - julia --color=yes -e 'cd(Pkg.dir("NodeNumbering")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    - julia --color=yes -e 'cd(Pkg.dir("NodeNumbering", "docs")); include("deploy.jl")'
