language: julia
os:
    - linux
julia:
    - release
    - nightly
after_success:
    - julia -e 'Pkg.add("Coverage")'
    - julia -e 'cd(Pkg.dir("NodeNumbering")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("NodeNumbering")); using Documenter; include(joinpath("docs", "make.jl"))'
    - julia -e 'Pkg.add("Lint")'
    - julia --color=yes -e 'cd(Pkg.dir("NodeNumbering")); using Lint; include(joinpath("test", "run_lint.jl"))'
