language: julia
os:
    - linux
julia:
    - release
    - nightly
    - 0.5.2
after_success:
    - julia -e 'cd(Pkg.dir("$name")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
